namespace JsUtils.Implementation.Tokens;

public static class Tags
{
    public const int Break = 256,
                     Else = 257,
                     For = 258,
                     While = 259,
                     Switch = 260,
                     Case = 261,
                     Do = 262,
                     Id = 263,
                     Number = 264,
                     String = 265,
                     Regex = 266,
                     True = 267,
                     False = 268,
                     Function = 269,
                     Return = 270,
                     Var = 271,
                     Let = 272,
                     Const = 273,
                     GreaterOrEqual = 274,
                     LessOrEqual = 275,
                     Equality = 276,
                     StrongEquality = 277,
                     And = 278,
                     Or = 279,
                     Increment = 280,
                     Decrement = 281,
                     New = 282,
                     Undefined = 283,
                     Null = 284,
                     If = 285,
                     Bool = 286,
                     Type = 287,
                     Comment = 288;
}